### ISSUE TITLE
Clicking a Radial Menu Item when using AHSS/APG causes player to attack

### ISSUE THREAD

**Issue by rc174945** [AoTTG-2/Aottg2-Unity#9] opened 2023-11-26 05:33 UTC
Prevent left click from activating attack when clicking emotes

**Comment by gisketch** [comment] 2023-11-27 17:15
https://github.com/AoTTG-2/Aottg2-Unity/assets/78424395/4b55ea84-5d91-4ddc-ba2f-7eb62ecdba60

_Removed the CD in the video._

Been trying to replicate this, but cannot. The last three times the character did attack in the video was when i double clicked it quick. Could be a mouse hardware problem for some? Would like to confirm if this still occurs on you guys' end?

**Comment by Adonca2203** [comment] 2023-12-03 17:47
I've also been trying to replicate this and the only time he attacks is when I double click not sure how fixable this is if we can't reproduce it

**Comment by BLuRTuts** [comment] 2023-12-07 15:10
For the record. This also happens with all cl inputs while in any menu or chat. Don't know if that should be fixed as well

**Comment by Adonca2203** [comment] 2023-12-07 16:30
Have we found a way to reliably reproduce this? Why was it reopened?

**Comment by Z-XINY** [comment] 2023-12-08 08:08
> Have we found a way to reliably reproduce this? Why was it reopened?

You can try clicking emotes when using AHSS weapon. I can actually only replicate this bug when using AHSS.

Uploading Aottest_bug_-_Trim.mp4…

**Closed** 2024-01-01 10:20 UTC
Labels: bug
